name: Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 强制递归拉取子模块
          fetch-depth: 0        # 完整拉取历史（某些主题需要）

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm  # 使用官方推荐缓存方式

      - name: Install Dependencies
        run: |
          npm install hexo --save  # 确保本地安装 Hexo 核心
          npm install --force      # 强制安装所有依赖

      # 关键修复：主题依赖处理
      - name: Install Theme Dependencies
        run: |
          cd themes/your-theme-name  # 替换为你的主题目录名
          npm install

      - name: Build Site
        run: |
          hexo clean
          hexo generate --debug  # 显示详细生成日志

      # 构建验证步骤
      - name: Verify Build Output
        run: |
          ls -alh public/
          grep -r "DOCTYPE html" public/  # 确认存在 HTML 文件

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2  # 修正为最新 v2 版本
        with:
          path: ./public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2  # 保持版本一致性
